Repository roclub/helm-charts, pull requests merged in 2024-09, with the labels that each got.

#85 chore: bumped conf2 to 0.3.0
  charts/roclub-conference2/Chart.yaml
Labels: size/XS

#86 chore: bumped conf2 version
  charts/roclub-conference2/Chart.yaml
Labels: size/XS

#87 chore: bumped conf2 version
  charts/roclub-conference2/Chart.yaml
Labels: size/XS, kind/chore

#89 chore: added livekit info to helm chart
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/connector-status/config.yaml
  charts/controlplane/templates/remote-control/config.yaml
  charts/controlplane/values.yaml
Labels: size/S, kind/chore

#90 feat: Added OIDC and redirection
  charts/knowledgebase/templates/NOTES.txt
  charts/knowledgebase/templates/dns_record.yaml
  charts/knowledgebase/templates/envoy-gateway/gateway.yaml
  charts/knowledgebase/templates/ingress.yaml
  charts/knowledgebase/templates/route.yaml
  charts/knowledgebase/templates/security_policy.yaml
  charts/knowledgebase/values.yaml
Labels: size/M, kind/feat

#91 chore: update KB version
  charts/knowledgebase/Chart.yaml
Labels: kind/chore

#92 fix: Knowledgebase OIDC and redirection
  charts/knowledgebase/Chart.yaml
  charts/knowledgebase/templates/dns_record.yaml
  charts/knowledgebase/templates/security_policy.yaml
  charts/knowledgebase/values.yaml
Labels: size/S, kind/fix

#93 fix: Knowledgebase traffic
  charts/knowledgebase/Chart.yaml
  charts/knowledgebase/templates/envoy-gateway/gateway.yaml
Labels: size/XS, kind/fix

#95 fix: Knowledgebase Let's Enctypt Production Server
  charts/knowledgebase/Chart.yaml
  charts/knowledgebase/templates/envoy-gateway/gateway.yaml
Labels: size/XS, kind/fix

#96 chore: updated KB for knowledgebase charts
  .github/CODEOWNERS
Labels: size/XS, kind/chore

#97 fix: Knowledgebase Refs to LoadBalancer
  charts/knowledgebase/Chart.yaml
  charts/knowledgebase/templates/envoy-gateway/gateway.yaml
Labels: size/XS, kind/fix

#98 fix: Knowledgebase Refs to LoadBalancer
  charts/knowledgebase/Chart.yaml
  charts/knowledgebase/templates/dns_record.yaml
Labels: size/XS, kind/fix

#100 fix: OIDC Redirecting
  charts/knowledgebase/Chart.yaml
  charts/knowledgebase/templates/route.yaml
  charts/knowledgebase/templates/security_policy.yaml
  charts/knowledgebase/values.yaml
Labels: size/S, kind/fix

#103 fix: KB Syntax Error in Helm Chart
  charts/knowledgebase/Chart.yaml
  charts/knowledgebase/templates/route.yaml
Labels: size/S, kind/fix

#105 feat: add new authz service to controlplane
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/_helpers.tpl
  charts/controlplane/templates/authz/config.yaml
  charts/controlplane/templates/authz/deployment.yaml
  charts/controlplane/templates/authz/hpa.yaml
  charts/controlplane/templates/authz/route.yaml
  charts/controlplane/templates/authz/service.yaml
  charts/controlplane/templates/authz/service_account.yaml
  charts/controlplane/templates/connector-control/config.yaml
  charts/controlplane/templates/connector-status/config.yaml
  charts/controlplane/templates/connector-status/deployment.yaml
  charts/controlplane/templates/remote-control/config.yaml
  charts/controlplane/templates/security_policy.yaml
  charts/controlplane/values.yaml
Labels: size/M, kind/feat

#106 feat: OpenFGA for Controlplane
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/_helpers.tpl
  charts/controlplane/templates/authz/config.yaml
  charts/controlplane/templates/authz/deployment.yaml
  charts/controlplane/templates/authz/hpa.yaml
  charts/controlplane/templates/authz/route.yaml
  charts/controlplane/templates/authz/service.yaml
  charts/controlplane/templates/authz/service_account.yaml
  charts/controlplane/templates/connector-control/config.yaml
  charts/controlplane/templates/connector-status/config.yaml
  charts/controlplane/templates/connector-status/deployment.yaml
  charts/controlplane/templates/remote-control/config.yaml
  charts/controlplane/templates/security_policy.yaml
  charts/controlplane/values.yaml
Labels: kind/feat

#108 refactor: Controlplane Template Naming
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/authz/route.yaml
  charts/controlplane/templates/connector-control/route.yaml
  charts/controlplane/templates/connector-status/config.yaml
  charts/controlplane/templates/connector-status/deployment.yaml
  charts/controlplane/templates/connector-status/route.yaml
  charts/controlplane/templates/dns/dns_record.yaml
  charts/controlplane/templates/gateway.yaml
  charts/controlplane/templates/influxdb2/auth.yaml
  charts/controlplane/templates/remote-control/route.yaml
  charts/controlplane/templates/security_policy.yaml
Labels: size/S, kind/refactor

#109 feat: Conference via Envoy Gateway
  charts/roclub-conference2/Chart.yaml
  charts/roclub-conference2/templates/frontend/dns.yaml
  charts/roclub-conference2/templates/frontend/ingress.yaml
  charts/roclub-conference2/templates/gateway.yaml
  charts/roclub-conference2/templates/route.yaml
  charts/roclub-conference2/values.yaml
Labels: size/M, kind/feat

#110 chore: conference chart target
  charts/roclub-conference/Chart.yaml
  charts/roclub-conference/templates/backend/deployment.yaml
  charts/roclub-conference/templates/backend/ingress.yaml
  charts/roclub-conference/templates/backend/service.yaml
  charts/roclub-conference/templates/frontend/dns.yaml
  charts/roclub-conference/templates/frontend/ingress.yaml
  charts/roclub-conference/templates/gateway.yaml
  charts/roclub-conference/templates/route.yaml
  charts/roclub-conference/values.yaml
  charts/roclub-conference2/.helmignore
  charts/roclub-conference2/templates/NOTES.txt
  charts/roclub-conference2/templates/_helpers.tpl
  charts/roclub-conference2/templates/frontend/deployment.yaml
  charts/roclub-conference2/templates/frontend/nginx.conf.yaml
  charts/roclub-conference2/templates/frontend/service.yaml
  charts/roclub-conference2/templates/serviceaccount.yaml
Labels: size/L, kind/chore

#113 fix: Conference Fix
  charts/roclub-conference/Chart.yaml
  charts/roclub-conference/templates/route.yaml
  charts/roclub-conference2/Chart.yaml
  charts/roclub-conference2/templates/frontend/dns.yaml
  charts/roclub-conference2/templates/gateway.yaml
  charts/roclub-conference2/values.yaml
Labels: size/M, kind/fix

#115 fix: CORS for Controlplane
  charts/controlplane/templates/security_policy.yaml
Labels: size/S, kind/fix

#116 fix: JWT for Controlplane
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/security_policy.yaml
Labels: size/XS, kind/fix

#117 fix: CORS for Controlplane
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/security_policy.yaml
Labels: size/XS, kind/fix

#119 chore: bump controlplane version
  charts/controlplane/Chart.yaml
Labels: size/XS, kind/chore

#122 chore: bump controlplane version
  charts/controlplane/Chart.yaml
Labels: size/XS, kind/chore

#123 chore: bump chart version for controlplane
  charts/controlplane/Chart.yaml
Labels: size/XS, kind/chore

#125 fix: Knowledgebase oauth
  charts/knowledgebase/Chart.yaml
  charts/knowledgebase/templates/route.yaml
  charts/knowledgebase/templates/security_policy.yaml
  charts/knowledgebase/values.yaml
Labels: size/S, kind/fix

#127 fix: Knowledgebase redirects
  charts/knowledgebase/Chart.yaml
  charts/knowledgebase/templates/dns_record.yaml
  charts/knowledgebase/templates/route.yaml
  charts/knowledgebase/values.yaml
Labels: size/S, kind/fix

#129 fix: oauth2 Callback endpoint removed
  charts/knowledgebase/Chart.yaml
  charts/knowledgebase/templates/route.yaml
  charts/knowledgebase/templates/security_policy.yaml
Labels: size/S, kind/fix

#130 chore: bump controlplane version
  charts/controlplane/Chart.yaml
Labels: size/XS, kind/chore
