Repository roclub/helm-charts, pull requests merged in 2024-11, with the labels that each got.

#148 fix: Controlplane Certificates not being Registered
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/gateway.yaml
Labels: size/S, kind/fix

#149 fix: Controlplane Certificates not being Registered - hostname fix
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/gateway.yaml
Labels: size/XS, kind/fix

#150 fix: Knowledgebase MultiHost
  charts/knowledgebase/Chart.yaml
  charts/knowledgebase/templates/NOTES.txt
  charts/knowledgebase/templates/dns_record.yaml
  charts/knowledgebase/templates/envoy-gateway/gateway.yaml
  charts/knowledgebase/templates/route.yaml
  charts/knowledgebase/values.yaml
Labels: size/S, kind/fix

#151 fix: OAuth2 Flow DE
  charts/knowledgebase/Chart.yaml
  charts/knowledgebase/templates/route.yaml
  charts/knowledgebase/templates/security_policy.yaml
Labels: size/S, kind/fix

#152 chore: Chart Update for New App Version
  charts/roclub-conference/Chart.yaml
Labels: size/XS, kind/chore

#155 chore: bump conference to 0.7.18
  charts/roclub-conference/Chart.yaml
Labels: size/XS, kind/chore

#153 chore: bump chart version for controlplane
  charts/controlplane/Chart.yaml
Labels: size/XS, kind/chore

#156 chore: update chart for KB version bump
  charts/knowledgebase/Chart.yaml
Labels: size/XS, kind/chore

#157 chore: conference bump version 0.7.19
  charts/roclub-conference/Chart.yaml
Labels: size/XS

#158 fix: allow origins with localhost for dev
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/security_policy.yaml
Labels: size/XS, kind/fix

#161 chore: version bump KB
  charts/knowledgebase/Chart.yaml
Labels: size/XS

#162 chore: bump controlplane version
  charts/controlplane/Chart.yaml
Labels: size/XS, kind/chore

#163 chore: Bump Version of Conference to 0.8.0
  charts/roclub-conference/Chart.yaml
Labels: size/XS, kind/chore

#166 chore: bumped chart version
  charts/roclub-conference/Chart.yaml
Labels: size/XS, kind/chore
