Repository roclub/helm-charts, pull requests merged in 2024-08, with the labels that each got.

#68 fix: Knowledgebase Multi Hosts Deployment
  .gitignore
  README.md
  charts/knowledgebase/Chart.yaml
  charts/knowledgebase/templates/dns_record.yaml
  charts/knowledgebase/values.yaml
  charts/roclub-auth0-service/values.yaml
  charts/roclub-conference2/values.yaml
Labels: size/S

#69 fix: knowledgebase versioning
  charts/knowledgebase/Chart.yaml
Labels: size/XS

#71 chore: bump version conference2
  charts/roclub-conference2/Chart.yaml
Labels: size/XS

#72 fix: bumped version
  charts/roclub-conference2/values.yaml
Labels: size/XS

#73 fix: chart version
  charts/roclub-conference2/Chart.yaml
Labels: size/XS

#74 feat: DNS via Crossplane
  charts/roclub-conference2/templates/frontend/dns.yaml
Labels: size/S

#75 chore: bump version of conference2 chart
  charts/roclub-conference2/Chart.yaml
  charts/roclub-conference2/values.yaml
Labels: size/XS

#76 fix: bumped conf2 version 0.1.15
  charts/roclub-conference2/Chart.yaml
Labels: size/XS

#77 chore: bumped kb version
  charts/knowledgebase/Chart.yaml
Labels: size/XS

#78 chore: bumped conf2 version
  charts/roclub-conference2/Chart.yaml
Labels: size/XS

#79 chore: bumped conf2 to 0.2.1
  charts/roclub-conference2/Chart.yaml
Labels: size/XS

#80 feat: Helm Chart to Work with Envoy Gateway
  charts/controlplane/Chart.yaml
  charts/controlplane/crds/crossplane.yaml
  charts/controlplane/templates/NOTES.txt
  charts/controlplane/templates/connector-control/config.yaml
  charts/controlplane/templates/connector-control/deployment.yaml
  charts/controlplane/templates/connector-control/route.yaml
  charts/controlplane/templates/connector-control/service.yaml
  charts/controlplane/templates/connector-control/service_account.yaml
  charts/controlplane/templates/connector-status/config.yaml
  charts/controlplane/templates/connector-status/deployment.yaml
  charts/controlplane/templates/connector-status/ingress.yaml
  charts/controlplane/templates/connector-status/route.yaml
  charts/controlplane/templates/connector-status/service.yaml
  charts/controlplane/templates/dns/dns_record.yaml
  charts/controlplane/templates/gateway.yaml
  charts/controlplane/templates/grafana/influx_pdc.yaml
  charts/controlplane/templates/grafana/secret.yaml
  charts/controlplane/templates/influxdb2/auth.yaml
  charts/controlplane/templates/middlewares.yaml
  charts/controlplane/templates/remote-control/config.yaml
  charts/controlplane/templates/remote-control/deployment.yaml
  charts/controlplane/templates/remote-control/gateway_deployment.yaml
  charts/controlplane/templates/remote-control/gateway_ervice.yaml
  charts/controlplane/templates/remote-control/gateway_hpa.yaml
  charts/controlplane/templates/remote-control/gateway_ingress.yaml
  charts/controlplane/templates/remote-control/gateway_serviceaccount.yaml
  charts/controlplane/templates/remote-control/route.yaml
  charts/controlplane/templates/remote-control/service.yaml
  charts/controlplane/values.yaml
Labels: size/L

#83 chore: bumped conf2 0.2.2
  charts/roclub-conference2/Chart.yaml
Labels: size/XS

#82 feat: add probes for controlplane
  charts/controlplane/templates/connector-control/deployment.yaml
  charts/controlplane/templates/connector-status/deployment.yaml
  charts/controlplane/templates/remote-control/deployment.yaml
Labels: size/S
