Repository roclub/helm-charts, pull requests merged in 2024-12, with the labels that each got.

#172 fix: replace : by = in toml config
  charts/controlplane/templates/authz/config.yaml
  charts/controlplane/templates/connector-control/config.yaml
  charts/controlplane/templates/connector-status/config.yaml
  charts/controlplane/templates/remote-control/config.yaml
Labels: size/S, kind/fix

#173 chore: bump controlplane helm chart
  charts/controlplane/Chart.yaml
Labels: size/XS, kind/chore

#174 fix: variable to be correctly interpreted as list, not as string
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/authz/config.yaml
  charts/controlplane/templates/connector-control/config.yaml
  charts/controlplane/templates/connector-status/config.yaml
  charts/controlplane/templates/remote-control/config.yaml
Labels: size/S, kind/fix

#175 fix: Controlplane Zitadel JWKS URL
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/security_policy.yaml
Labels: size/XS, kind/fix

#180 chore: bump conference helm chart
  charts/roclub-conference/Chart.yaml
Labels: size/XS, kind/chore

#181 chore: bump controlplane app version to apply fix
  charts/controlplane/Chart.yaml
Labels: size/XS, kind/chore

#183 chore: bumped conference helm chart
  charts/roclub-conference/Chart.yaml
Labels: size/XS, kind/chore

#187 chore: version bump KB
  charts/knowledgebase/Chart.yaml
Labels: size/XS, kind/chore

#186 chore: bump controlplane app version to 2.8.3
  charts/controlplane/Chart.yaml
Labels: size/XS, kind/chore
