Repository roclub/helm-charts, pull requests merged in 2024-10, with the labels that each got.

#131 fix: Knowledgebase redirect
  charts/knowledgebase/Chart.yaml
  charts/knowledgebase/templates/route.yaml
  charts/knowledgebase/templates/security_policy.yaml
Labels: size/S, kind/fix

#132 fix: CORS maxAge for Controlplane
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/security_policy.yaml
Labels: size/XS, kind/fix

#133 chore: bump controlplane version
  charts/controlplane/Chart.yaml
Labels: size/XS, kind/chore

#135 chore: Remove Grafana PDC Agent from Chart
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/grafana/influx_pdc.yaml
  charts/controlplane/templates/grafana/secret.yaml
Labels: size/S, kind/chore

#136 feat: Multiple DNS Records for Controlplane
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/authz/route.yaml
  charts/controlplane/templates/connector-control/route.yaml
  charts/controlplane/templates/connector-status/route.yaml
  charts/controlplane/templates/dns/dns_record.yaml
  charts/controlplane/templates/remote-control/route.yaml
  charts/controlplane/values.yaml
Labels: size/S, kind/feat

#140 fix: Remove Authentication from CORS options endpoint
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/authz/route.yaml
  charts/controlplane/templates/conference-websocket/route.yaml
  charts/controlplane/templates/connector-control/route.yaml
  charts/controlplane/templates/connector-status/route.yaml
  charts/controlplane/templates/preflight_cors_rule.yaml
  charts/controlplane/templates/remote-control/route.yaml
  charts/controlplane/templates/security_policy.yaml
Labels: size/M, kind/fix

#143 fix: Target Selectors for SecurityPolicy
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/security_policy.yaml
  charts/roclub-conference/Chart.yaml
  charts/roclub-conference/templates/_helpers.tpl
  charts/roclub-conference/templates/deployment.yaml
  charts/roclub-conference/templates/dns.yaml
  charts/roclub-conference/templates/frontend/dns.yaml
  charts/roclub-conference/templates/frontend/service.yaml
  charts/roclub-conference/templates/gateway.yaml
  charts/roclub-conference/templates/nginx.conf.yaml
  charts/roclub-conference/templates/route.yaml
  charts/roclub-conference/templates/service.yaml
  charts/roclub-conference/values.yaml
Labels: size/M, kind/fix

#144 fix: Target Selectors for SecurityPolicy as array
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/security_policy.yaml
Labels: size/XS, kind/fix

#145 fix: Websocket CORS
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/preflight_cors_rule.yaml
Labels: size/S, kind/fix

#146 chore: bump controlplane version
  charts/controlplane/Chart.yaml
Labels: size/XS, kind/chore
