Repository roclub/helm-charts, pull requests merged in 2024-07, with the labels that each got.

#59 feat: InfluxDB with DNS Record configured via Crossplane/roclub Platform API
  charts/controlplane/Chart.lock
  charts/controlplane/Chart.yaml
  charts/controlplane/charts/influxdb2-2.1.2.tgz
  charts/controlplane/crds/crossplane.yaml
  charts/controlplane/templates/dns/dns_record.yaml
  charts/controlplane/templates/dns/provider_config.yaml
  charts/controlplane/values.yaml
Labels: size/M

#60 feat: Knowledgebase Helm Chart
  charts/knowledgebase/.helmignore
  charts/knowledgebase/Chart.yaml
  charts/knowledgebase/templates/NOTES.txt
  charts/knowledgebase/templates/_helpers.tpl
  charts/knowledgebase/templates/deployment-de.yaml
  charts/knowledgebase/templates/deployment.yaml
  charts/knowledgebase/templates/dns_record.yaml
  charts/knowledgebase/templates/ingress.yaml
  charts/knowledgebase/templates/service.yaml
  charts/knowledgebase/templates/serviceaccount.yaml
  charts/knowledgebase/templates/tests/test-connection.yaml
  charts/knowledgebase/values.yaml
Labels: size/M

#61 fix: Helm Chart Releaser Action
  .github/workflows/helm-releaser.yml
Labels: size/S

#63 chore: bumped knowledgebase to the moon
  charts/knowledgebase/Chart.yaml
Labels: size/XS

#65 feat: added conference2 service
  charts/roclub-conference2/.helmignore
  charts/roclub-conference2/Chart.yaml
  charts/roclub-conference2/templates/NOTES.txt
  charts/roclub-conference2/templates/_helpers.tpl
  charts/roclub-conference2/templates/frontend/deployment.yaml
  charts/roclub-conference2/templates/frontend/ingress.yaml
  charts/roclub-conference2/templates/frontend/nginx.conf.yaml
  charts/roclub-conference2/templates/frontend/service.yaml
  charts/roclub-conference2/templates/serviceaccount.yaml
  charts/roclub-conference2/values.yaml
Labels: size/M

#66 chore: bump KB
  charts/knowledgebase/Chart.yaml
Labels: size/XS

#67 fix: label selector
  charts/knowledgebase/Chart.yaml
  charts/knowledgebase/templates/_helpers.tpl
  charts/knowledgebase/templates/deployment.yaml
  charts/knowledgebase/templates/service.yaml
Labels: size/S
