Repository roclub/helm-charts, pull requests merged in 2025-06, with the labels that each got.

#296 chore: bumped conf helm chart
  charts/roclub-conference/Chart.yaml
Labels: size/XS, kind/chore

#298 chore: Delete charts/roclub-auth0-service
  charts/roclub-auth0-service/.helmignore
  charts/roclub-auth0-service/Chart.yaml
  charts/roclub-auth0-service/templates/_helpers.tpl
  charts/roclub-auth0-service/templates/deployment.yaml
  charts/roclub-auth0-service/templates/ingress.yaml
  charts/roclub-auth0-service/templates/service.yaml
  charts/roclub-auth0-service/templates/serviceaccount.yaml
  charts/roclub-auth0-service/values.yaml
Labels: size/M, kind/chore, stale

#310 chore: bumped conf helm chart
  charts/roclub-conference/Chart.yaml
Labels: kind/chore

#302 fix: jwks retry and fetch config on dev
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/security_policy.yaml
Labels: size/XS, kind/fix
