Repository roclub/helm-charts, pull requests merged in 2025-03, with the labels that each got.

#237 chore: Bump Knowledgebase Version to 0.9.2
  charts/knowledgebase/Chart.yaml
Labels: size/XS, kind/chore

#238 chore: bump version of conference to 0.12.2
  charts/roclub-conference/Chart.yaml
Labels: size/XS, kind/chore

#239 chore: bump controlplane app version to 2.9.4
  charts/controlplane/Chart.yaml
Labels: size/XS, kind/chore

#240 chore: Bump Knowledgebase Version to 0.9.3
  charts/knowledgebase/Chart.yaml
Labels: size/XS, kind/chore

#241 chore: Bump Knowledgebase Version to 0.9.4
  charts/knowledgebase/Chart.yaml
Labels: size/XS, kind/chore

#245 fix: CORS Notifications
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/preflight_cors_rule.yaml
Labels: size/S, kind/fix

#247 fix: wrong backendref for preflight rule
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/preflight_cors_rule.yaml
Labels: size/XS, kind/fix

#249 chore: bump controlplane app version to 2.10.2
  charts/controlplane/Chart.yaml
Labels: size/XS, kind/chore

#251 fix: expose notifications grpc port
  charts/controlplane/Chart.yaml
  charts/controlplane/templates/notifications/deployment.yaml
Labels: size/XS

#252 chore: bump KB version
  charts/knowledgebase/Chart.yaml
Labels: kind/chore

#253 chore: bump controlplane version to 2.10.3
  charts/controlplane/Chart.yaml
Labels: size/XS, kind/chore

#242 feat: cronjob for AWS IoT network interface script
  charts/controlplane/templates/connector-status/AWS_interface_cronjob.yaml
  charts/controlplane/templates/connector-status/service_account_iot_kafka_script.yaml
  charts/controlplane/values.yaml
Labels: size/S, kind/feat

#255 chore: bump controlplane helm chart to deploy cronjob
  charts/controlplane/Chart.yaml
Labels: size/XS, kind/chore
