Repository roclub/helm-charts, pull requests merged in 2025-04, with the labels that each got.

#259 chore: bump KB version
  charts/knowledgebase/Chart.yaml
Labels: size/XS, kind/chore

#260 chore: Bump Conference to 0.14.1
  charts/roclub-conference/Chart.yaml
Labels: size/XS, kind/chore

#262 chore: bump conference helm chart
  charts/roclub-conference/Chart.yaml
Labels: size/XS, kind/chore

#263 feat: added /compliance to paths to be in scope for authN
  charts/knowledgebase/templates/route.yaml
Labels: size/XS, kind/feat

#266 chore: bump controlplane version
  charts/controlplane/Chart.yaml
Labels: size/XS, kind/chore

#267 chore: bump controlplane version
  charts/controlplane/Chart.yaml
Labels: kind/chore

#268 chore: bump controlplane version
  charts/controlplane/Chart.yaml
Labels: size/XS, kind/chore

#269 chore: Bump Conference to 0.15.0
  charts/roclub-conference/Chart.yaml
Labels: size/XS, kind/chore
